CREATE DATABASE MOEDA_ESTUDANTIL; 


CREATE TABLE USUARIO (
  LOGIN int(10) NOT NULL,
  NOME VARCHAR(60) NOT NULL,
  SENHA VARCHAR(12) NOT NULL,
  PRIMARY KEY(LOGIN)
) ENGINE=InnoDB;

CREATE TABLE ALUNO(
 CPF VARCHAR(20) NOT NULL,
 EMAIL VARCHAR(50) NOT NULL, 
 RG VARCHAR(20) NOT NULL,
 ENDERECO VARCHAR(100) NOT NULL,
 CURSO VARCHAR(20) NOT NULL,
 LOGIN_USUARIO int(10) NOT NULL,   
 PRIMARY KEY(CPF),/* CHAVE PRIMARIA*/
 foreign key(LOGIN_USUARIO) references USUARIO(LOGIN)/*CHAVE ESTRANGEIRA*/
 )ENGINE=InnoDB;

CREATE TABLE PROFESSOR(
 CPF VARCHAR(20) NOT NULL,
 MOEDAS DOUBLE(9,2), 
 DEPARTAMENTO VARCHAR(20) NOT NULL,
 LOGIN_USUARIO int(10) NOT NULL,   
 PRIMARY KEY(CPF),/* CHAVE PRIMARIA*/
 foreign key(LOGIN_USUARIO) references USUARIO(LOGIN)/*CHAVE ESTRANGEIRA*/
 )ENGINE=InnoDB;


CREATE TABLE INSTITUICAO(
 CNPJ VARCHAR(20) NOT NULL,
 LOGIN_USUARIO int(10) NOT NULL, 
 CPF_ALUNO VARCHAR(20) NOT NULL,
 CPF_PROFESSOR VARCHAR(20) NOT NULL,
 PRIMARY KEY(CNPJ),/* CHAVE PRIMARIA*/
 foreign key(LOGIN_USUARIO) references USUARIO(LOGIN),/*CHAVE ESTRANGEIRA*/
 foreign key(CPF_ALUNO) references ALUNO(CPF),/*CHAVE ESTRANGEIRA*/
 foreign key(CPF_PROFESSOR) references PROFESSOR(CPF)/*CHAVE ESTRANGEIRA*/
 )ENGINE=InnoDB;

 CREATE TABLE PRODUTO(
 ID INT UNSIGNED AUTO_INCREMENT  NOT NULL,
 CUSTO_MOEDAS INT(5) NOT NULL,
 FOTO BLOB,
 NOME varchar(60) NOT NULL,
 DESCRICAO varchar(60) NOT NULL,
 CNPJ_INSTITUICAO VARCHAR(20) NOT NULL,    
 PRIMARY KEY(ID),/* CHAVE PRIMARIA*/
 foreign key(CNPJ_INSTITUICAO) references INSTITUICAO(CNPJ)/*CHAVE ESTRANGEIRA*/
 )ENGINE=InnoDB;