CREATE DATABASE MOEDA_ESTUDANTIL; 


CREATE TABLE USUARIO(
  LOGIN int(10) NOT NULL,
  NOME varchar(60) NOT NULL,
  SENHA VARCHAR(12) NOT NULL,
  PRIMARY KEY(LOGIN)
) ENGINE=InnoDB;

CREATE TABLE INSTITUICAO(
ID INT UNSIGNED AUTO_INCREMENT  NOT NULL,
NOME VARCHAR(60) NOT NULL,
PRIMARY KEY(ID)
) ENGINE=InnoDB;

CREATE TABLE ALUNO(
 CPF INT(11) NOT NULL,
 EMAIL VARCHAR(20) NOT NULL, 
 RG INT(8) NOT NULL,
 ENDERECO VARCHAR(60) NOT NULL,
 CURSO VARCHAR(20) NOT NULL,
 MOEDAS INT(10),
 LOGIN_USUARIO int(10) NOT NULL,   
 ID_INSTITUICAO INT UNSIGNED NOT NULL,
 PRIMARY KEY(CPF),/* CHAVE PRIMARIA*/
 foreign key(LOGIN_USUARIO) references USUARIO(LOGIN),/*CHAVE ESTRANGEIRA*/
 foreign key(ID_INSTITUICAO) references INSTITUICAO(ID)/*CHAVE ESTRANGEIRA*/
 )ENGINE=InnoDB;

CREATE TABLE PROFESSOR(
 CPF INT(11) NOT NULL,
 MOEDAS INT(10),  
 DEPARTAMENTO VARCHAR(20) NOT NULL,
 LOGIN_USUARIO int(10) NOT NULL,
 ID_INSTITUICAO INT UNSIGNED NOT NULL,   
 PRIMARY KEY(CPF),/* CHAVE PRIMARIA*/
 foreign key(LOGIN_USUARIO) references USUARIO(LOGIN),/*CHAVE ESTRANGEIRA*/
 foreign key(ID_INSTITUICAO) references INSTITUICAO(ID)/*CHAVE ESTRANGEIRA*/
 )ENGINE=InnoDB;


CREATE TABLE EMPRESA(
 CNPJ FLOAT(14) NOT NULL,
 NOME VARCHAR(60),
 LOGIN_USUARIO int(10) NOT NULL,
 PRIMARY KEY(CNPJ),/* CHAVE PRIMARIA*/
 foreign key(LOGIN_USUARIO) references USUARIO(LOGIN)/*CHAVE ESTRANGEIRA*/
 )ENGINE=InnoDB;

 CREATE TABLE VANTAGEM(
 ID INT UNSIGNED AUTO_INCREMENT  NOT NULL,
 CUSTO_MOEDAS INT(10) NOT NULL,
 FOTO BLOB,
 NOME varchar(60) NOT NULL,
 DESCRICAO varchar(60) NOT NULL,
 CNPJ_EMPRESA FLOAT(14) NOT NULL,    
 PRIMARY KEY(ID),/* CHAVE PRIMARIA*/
 foreign key(CNPJ_EMPRESA) references EMPRESA(CNPJ)/*CHAVE ESTRANGEIRA*/
 )ENGINE=InnoDB;







